# This file and all contents in it are OPTIONAL.

# The default namespace to apply to resources that are namespaced
# but do not specify a namespace.  In this example no resources
# are configured with a namespace so this default will apply
namespace: fleet-manifest-example


diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: Deployment
    operations:
    # Ignore the replicas differeces
    - {"op": "remove", "path": "/spec/replicas"}    
